# Generated by Django 4.2 on 2023-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Phone',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
